Create Code_Checking_Program.cpp
As you write your code, it is very easy to leave out a parenthesis, bracket, or curly brace. To help solve this problem, this simple program will check to make sure all the parentheses, brackets, and curly braces lineup.
Here are a few examples:
(([ ] ({ }))) - Valid
(([ )]) - Invalid because the square bracket needs to close before the parentheses can close.
[(()) - Invalid because the square brackets are not balanced.

Sample Output 1:
Please enter a file to check: GoodCode.txt
Your code looks good!

Sample Output 2:
Please enter a file to check: BadCode.txt
Error: Line: 21 Expecting } but found )